<a href="https://colab.research.google.com/github/Jhon4t4nEmbus/Talento_Tech/blob/main/Conexi%C3%B3n/regresi%C3%B3nlineal_multiple.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Imporar las librerias y crear el Data frame

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
y =(78.5,74.3,104.3,87.6,95.9,109.2,102.7,72.5,93.1,115.9,83.8,113.3,109.4)
x1 =(7,1,11,11,7,11,3,1,2,21,1,11,10)
x2 =(26,29,56,31,52,55,71,31,54,47,40,66,68)
x3 =(6,15,8,8,6,9,17,22,18,4,23,9,8)
x4 =(60,52,20,47,33,22,6,44,22,26,34,12,12)
df = pd.DataFrame({
    "y":y,
    "x1":x1,
    "x2":x2,
    "x3":x3,
    "x4":x4
    })
df


y  x1  x2  x3  x4
0    78.5   7  26   6  60
1    74.3   1  29  15  52
2   104.3  11  56   8  20
3    87.6  11  31   8  47
4    95.9   7  52   6  33
5   109.2  11  55   9  22
6   102.7   3  71  17   6
7    72.5   1  31  22  44
8    93.1   2  54  18  22
9   115.9  21  47   4  26
10   83.8   1  40  23  34
11  113.3  11  66   9  12
12  109.4  10  68   8  12

In [ ]:
# Convertir la tabla en una matriz donde los Y sea =  1
df2= df.copy()
df2['y'] = 1
df2

y  x1  x2  x3  x4
0   1   7  26   6  60
1   1   1  29  15  52
2   1  11  56   8  20
3   1  11  31   8  47
4   1   7  52   6  33
5   1  11  55   9  22
6   1   3  71  17   6
7   1   1  31  22  44
8   1   2  54  18  22
9   1  21  47   4  26
10  1   1  40  23  34
11  1  11  66   9  12
12  1  10  68   8  12

In [ ]:
X = np.array(X)
print(X)

[[ 1  7 26  6 60]
 [ 1  1 29 15 52]
 [ 1 11 56  8 20]
 [ 1 11 31  8 47]
 [ 1  7 52  6 33]
 [ 1 11 55  9 22]
 [ 1  3 71 17  6]
 [ 1  1 31 22 44]
 [ 1  2 54 18 22]
 [ 1 21 47  4 26]
 [ 1  1 40 23 34]
 [ 1 11 66  9 12]
 [ 1 10 68  8 12]]


In [ ]:
# Hallar la transpuesta de x
Xt = X.T
print(Xt)

[[ 1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 7  1 11 11  7 11  3  1  2 21  1 11 10]
 [26 29 56 31 52 55 71 31 54 47 40 66 68]
 [ 6 15  8  8  6  9 17 22 18  4 23  9  8]
 [60 52 20 47 33 22  6 44 22 26 34 12 12]]


In [ ]:
xt_x = Xt @ X
determinant = np.linalg.det(xt_x)
print("Determinante de (x_transpose * x):")
display(determinant)
print(xt_x)


Determinante de (x_transpose * x):


np.float64(27717211679.99304)

[[   13    97   626   153   390]
 [   97  1139  4922   769  2620]
 [  626  4922 33050  7201 15739]
 [  153   769  7201  2293  4628]
 [  390  2620 15739  4628 15062]]


In [ ]:

# Calcular la inversa de xt_x
xt_x_inv = np.linalg.inv(xt_x)


print("Inversa de (x_transpose * x):")
print(xt_x_inv)


Inversa de (x_transpose * x):
[[ 8.20654575e+02 -8.44180186e+00 -8.45777985e+00 -8.63453878e+00
  -8.28974378e+00]
 [-8.44180186e+00  9.27104019e-02  8.56862094e-02  9.26373566e-02
   8.44549553e-02]
 [-8.45777985e+00  8.56862094e-02  8.75602572e-02  8.78666397e-02
   8.55980995e-02]
 [-8.63453878e+00  9.26373566e-02  8.78666397e-02  9.52014097e-02
   8.63919188e-02]
 [-8.28974378e+00  8.44549553e-02  8.55980995e-02  8.63919188e-02
   8.40311912e-02]]


In [ ]:
y= df['y'].values
betas = xt_x_inv @ Xt @ y
betas

array([62.4053693 ,  1.55110265,  0.51016758,  0.1019094 , -0.14406103])

In [ ]:
# calcular los errores
df['Y_pred'] = betas[0] + betas[1]*df['x1'] + betas[2]*df['x2'] + betas[3]*df['x3'] + betas[4]*df['x4']
df


y  x1  x2  x3  x4      Y_pred
0    78.5   7  26   6  60   78.495240
1    74.3   1  29  15  52   72.788799
2   104.3  11  56   8  20  105.970938
3    87.6  11  31   8  47   89.327100
4    95.9   7  52   6  33   95.649244
5   109.2  11  55   9  22  105.274557
6   102.7   3  71  17   6  104.148669
7    72.5   1  31  22  44   75.674989
8    93.1   2  54  18  22   91.721651
9   115.9  21  47   4  26  115.618452
10   83.8   1  40  23  34   81.809016
11  113.3  11  66   9  12  112.327011
12  109.4  10  68   8  12  111.694334

In [ ]:

df['Error'] = df['y'] - df['Y_pred']
df

y  x1  x2  x3  x4      Y_pred     Error
0    78.5   7  26   6  60   78.495240  0.004760
1    74.3   1  29  15  52   72.788799  1.511201
2   104.3  11  56   8  20  105.970938 -1.670938
3    87.6  11  31   8  47   89.327100 -1.727100
4    95.9   7  52   6  33   95.649244  0.250756
5   109.2  11  55   9  22  105.274557  3.925443
6   102.7   3  71  17   6  104.148669 -1.448669
7    72.5   1  31  22  44   75.674989 -3.174989
8    93.1   2  54  18  22   91.721651  1.378349
9   115.9  21  47   4  26  115.618452  0.281548
10   83.8   1  40  23  34   81.809016  1.990984
11  113.3  11  66   9  12  112.327011  0.972989
12  109.4  10  68   8  12  111.694334 -2.294334

In [ ]:
df['Error^2'] = df['Error']**2
df

y  x1  x2  x3  x4      Y_pred     Error    Error^2
0    78.5   7  26   6  60   78.495240  0.004760   0.000023
1    74.3   1  29  15  52   72.788799  1.511201   2.283728
2   104.3  11  56   8  20  105.970938 -1.670938   2.792032
3    87.6  11  31   8  47   89.327100 -1.727100   2.982875
4    95.9   7  52   6  33   95.649244  0.250756   0.062878
5   109.2  11  55   9  22  105.274557  3.925443  15.409100
6   102.7   3  71  17   6  104.148669 -1.448669   2.098642
7    72.5   1  31  22  44   75.674989 -3.174989  10.080552
8    93.1   2  54  18  22   91.721651  1.378349   1.899847
9   115.9  21  47   4  26  115.618452  0.281548   0.079269
10   83.8   1  40  23  34   81.809016  1.990984   3.964016
11  113.3  11  66   9  12  112.327011  0.972989   0.946708
12  109.4  10  68   8  12  111.694334 -2.294334   5.263969

In [ ]:
ErrorTotal = df['Error^2'].sum()
print(ErrorTotal)


47.86363935049883
